"""add repo side names

Revision ID: 60430e58fb41
Revises: b35766a66ec8
Create Date: 2017-12-30 23:55:17.865699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60430e58fb41'
down_revision = 'b35766a66ec8'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('side_a_name', sa.String(length=30), nullable=True))
    op.add_column('repository', sa.Column('side_b_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'side_b_name')
    op.drop_column('repository', 'side_a_name')
    # ### end Alembic commands ###
